package csomag;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Mikey
 */

public class Címmenü extends javax.swing.JFrame {
 private Statement sta; //ÚJ OLDAL
String host="jdbc:mysql://localhost:3306/vizsga";
String user="root";
String pass="root";



    public Címmenü() {
        initComponents();
        STARTMENU2.setVisible(false);
    
    }
    
    //OLDAL ELÉRÉS
      public Címmenü(Statement sta){
    initComponents();
    this.sta=sta;
     STARTMENU2.setVisible(false);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        STARTMENU1 = new javax.swing.JPanel();
        Cím = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        hatter1 = new javax.swing.JLabel();
        STARTMENU2 = new javax.swing.JPanel();
        kerdes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nevfield = new javax.swing.JTextField();
        evcombo = new javax.swing.JComboBox<>();
        allatcombo = new javax.swing.JComboBox<>();
        pontszám = new javax.swing.JTextField();
        Combokep = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        KEPEK = new javax.swing.JPanel();
        kep1 = new javax.swing.JPanel();
        fiú1 = new javax.swing.JLabel();
        kep2 = new javax.swing.JPanel();
        fiú3 = new javax.swing.JLabel();
        kep3 = new javax.swing.JPanel();
        lány1 = new javax.swing.JLabel();
        kep4 = new javax.swing.JPanel();
        lány2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Számithatsz rám!");
        setPreferredSize(new java.awt.Dimension(952, 800));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        STARTMENU1.setBorder(new javax.swing.border.MatteBorder(null));
        STARTMENU1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        STARTMENU1.setMaximumSize(new java.awt.Dimension(0, 0));
        STARTMENU1.setOpaque(false);
        STARTMENU1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cím.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Cím.setText("Számíthatsz rám!");
        STARTMENU1.add(Cím, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 440, 60));

        Start.setBackground(new java.awt.Color(255, 255, 0));
        Start.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        STARTMENU1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 210, 60));

        hatter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/JÁTÉK CÍM.png"))); // NOI18N
        hatter1.setPreferredSize(new java.awt.Dimension(854, 685));
        STARTMENU1.add(hatter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        getContentPane().add(STARTMENU1);
        STARTMENU1.setBounds(0, 0, 850, 685);

        STARTMENU2.setBackground(new java.awt.Color(102, 153, 255));
        STARTMENU2.setMaximumSize(new java.awt.Dimension(0, 0));
        STARTMENU2.setPreferredSize(new java.awt.Dimension(1196, 480));
        STARTMENU2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kerdes.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        kerdes.setText("Írd be a táblába az adataidat!");
        STARTMENU2.add(kerdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Hogy hívnak?");
        STARTMENU2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 170, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Hány éves vagy?");
        STARTMENU2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("kedvenc állatod?");
        STARTMENU2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 220, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Kezdő pontszám:");
        STARTMENU2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Válasz magadnak karaktert");
        STARTMENU2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, -1));

        nevfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nevfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevfieldActionPerformed(evt);
            }
        });
        STARTMENU2.add(nevfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 220, 50));

        evcombo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        evcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9" }));
        evcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evcomboActionPerformed(evt);
            }
        });
        STARTMENU2.add(evcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 60, 40));

        allatcombo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        allatcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kutya", "macska", "nyúl", "papagáj" }));
        STARTMENU2.add(allatcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 190, 40));

        pontszám.setEditable(false);
        pontszám.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pontszám.setText("0");
        STARTMENU2.add(pontszám, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, -1));

        Combokep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Combokep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01.PNG", "02.PNG", "03.PNG", "04.PNG" }));
        Combokep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombokepActionPerformed(evt);
            }
        });
        STARTMENU2.add(Combokep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 100, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("MEHET");
        jButton1.setPreferredSize(new java.awt.Dimension(1096, 498));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        STARTMENU2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 260, 60));

        KEPEK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kep1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fiú1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\01.PNG")); // NOI18N
        kep1.add(fiú1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        KEPEK.add(kep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        kep2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fiú3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\02.PNG")); // NOI18N
        kep2.add(fiú3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        KEPEK.add(kep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        kep3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lány1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\03.PNG")); // NOI18N
        kep3.add(lány1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        KEPEK.add(kep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        kep4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lány2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\04.PNG")); // NOI18N
        kep4.add(lány2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        KEPEK.add(kep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 160));

        STARTMENU2.add(KEPEK, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 140, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\MENU.png")); // NOI18N
        STARTMENU2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/magyarázóbót.png"))); // NOI18N
        STARTMENU2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 330, 320));

        getContentPane().add(STARTMENU2);
        STARTMENU2.setBounds(0, 2, 850, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
     hatter1.setVisible(false);//MEGJENITÉSI KANTINTÁS
   Start.setVisible(false);
   Cím.setVisible(false);
   STARTMENU2.setVisible(true);
  this.setSize(1110, 530);
  STARTMENU2.setSize(1110, 530);
   hang();
  
    }//GEN-LAST:event_StartActionPerformed

    private void evcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evcomboActionPerformed
       
    }//GEN-LAST:event_evcomboActionPerformed

    private void CombokepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombokepActionPerformed
  megjelenités();
    }//GEN-LAST:event_CombokepActionPerformed

    private void nevfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //adatok létrehozása
        Adatok();
        //KOR PANEL UGRÁS
        Korpanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Címmenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Címmenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Címmenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Címmenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Címmenü().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combokep;
    private javax.swing.JLabel Cím;
    private javax.swing.JPanel KEPEK;
    private javax.swing.JPanel STARTMENU1;
    private javax.swing.JPanel STARTMENU2;
    private javax.swing.JButton Start;
    private javax.swing.JComboBox<String> allatcombo;
    private javax.swing.JComboBox<String> evcombo;
    private javax.swing.JLabel fiú1;
    private javax.swing.JLabel fiú3;
    private javax.swing.JLabel hatter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel kep1;
    private javax.swing.JPanel kep2;
    private javax.swing.JPanel kep3;
    private javax.swing.JPanel kep4;
    private javax.swing.JLabel kerdes;
    private javax.swing.JLabel lány1;
    private javax.swing.JLabel lány2;
    private javax.swing.JTextField nevfield;
    private javax.swing.JTextField pontszám;
    // End of variables declaration//GEN-END:variables

    private void Adatok() {
//      int id=Integer.parseInt(Fieldszam.getText());  CSAK AKKOR AUTO_ICREMENT NÉLKÜL HASZNÁLÓD
      
String nev=nevfield.getText();
int eletkor=Integer.parseInt(evcombo.getSelectedItem().toString());
String allat_kedvenc=allatcombo.getSelectedItem().toString();
String avatarkep=Combokep.getSelectedItem().toString();
int pontszam=Integer.parseInt(pontszám.getText());

//ADATOK BEILESZTÉSE
try{
Connection con= DriverManager.getConnection(host,user,pass);
String sql="INSERT INTO játékosadatok (nev,eletkor,allat_kedvenc,avatarkep,pontszam)"
     + "VALUES ('"+nev+"',"+eletkor+",'"+allat_kedvenc+"','"+avatarkep+"',"+pontszam+")";  
     Statement sta=con.createStatement();
     sta.executeUpdate(sql);
     sta.close();
     con.close();
      JOptionPane.showMessageDialog(null, "Adatok elmentve jöhet a játék! :D ");
}

catch(SQLException hiba){
JOptionPane.showMessageDialog(null,"HiBA");
}
    }

    private void Korpanel() {
     Hetevesjatek het=new Hetevesjatek(sta);
Nyolcevesjatek nyolc=new Nyolcevesjatek(sta);
Kilencevesek kilenc=new Kilencevesek(sta);

Vége_és_vissza_az_elejére proba=new Vége_és_vissza_az_elejére(sta); //ellenőrzés

if(evcombo.getSelectedItem().equals("7"))
{het.setVisible(true);
dispose();}

if(evcombo.getSelectedItem().equals("8"))
{nyolc.setVisible(true);
dispose();}

if(evcombo.getSelectedItem().equals("9"))
{kilenc.setVisible(true);
dispose();}
    }

    private void megjelenités() {
         String kepszam=Combokep.getSelectedItem().toString();
         kep1.setVisible(false); kep2.setVisible(false); kep3.setVisible(false); kep4.setVisible(false);
         switch (kepszam) {
    case "01.PNG":
        kep1.setVisible(true);
        break;
    case "02.PNG":
        kep2.setVisible(true);
        break;
    case "03.PNG":
        kep3.setVisible(true);
        break;
    case "04.PNG":
        kep4.setVisible(true);
        break;
    default:
        break;
}
 

    }

    private void hang() {
      InputStream in;
try {
    String fileName = "src\\hangok\\PROMO.wav";
    switch (fileName) {
        case "src\\hangok\\PROMO.wav":
            in = new FileInputStream(new File(fileName));
            AudioStream ad = new AudioStream(in);
            AudioPlayer.player.start(ad);
            break;
        // Add additional cases for other file names if needed
        default:
            JOptionPane.showMessageDialog(null, "Hiba");
            break;
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(null, "Hiba");
}
    }

   
}
