/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csomag;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mikey
 */
public class Kilencevesek extends javax.swing.JFrame {
   private Statement sta;
   String host="jdbc:mysql://localhost:3306/vizsga";
String user="root";
String pass="root";
private int  ID;

//RÓMAI SZÁMOK
String[] tömb = {"I","II","III","IV","V","VI","VII","VIII","IX","X"};  //1-10

String[] tömb2 = {"XI","XII","XIII","XIV","XV","XVI","XVII","XVIII","XIX","XX"};//11-20

String[] tömb3 ={"XXI","XXII","XXIII","XXIV","XXV","XXVI","XXVII","XXVIII","XXIX","XXX"};//21-30

String[] tömb4 ={"XXXI","XXXII","XXXIII","XXXIV","XXXV","XXXVI","XXXVII","XXXVIII","XXXIX","XL"};//31-40

String[] tömb5 ={"XLI","XLII","XLIII","XLIV","XLV","XLVI","XLXVII","XLVIII","XLIX","L"};//41-50

String[] tömb6 ={"LI","LII","LIII","LIV","LV","LVI","LVII","LVIII","LIX","LX"};//51-60

String[] tömb7 ={"LXI","LXII","LXIII","LXIV","LXV","LXVI","LXVII","LXVIII","LXIX","LXX"};//61-70

String[] tömb8 ={"LXXI","LXXII","LXXIII","LXXIV","LXXV","LXXVI","LXXVII","LXXVIII","LXXIX","LXXX"};//71-80

String[] tömb9 ={"LXXXI","LXXXII","LXXXIII","LXXXIV","LXXXV","LXXXVI","LXXXVII","LXXXVIII","LXXXIX","XC"};//81-90

String[] tömb10 ={"XCI","XCII","XCIII","XCIV","XCV","XCVI","XCVII","XCVIII","XCIX","C"};//91-100
//-------------------------------------------------------------------------------------------------------------------
  
//10 RANDOM SZÖVEG GENERÁLÁSA
int szam=(int)(Math.random()*10);
int szam2=(int)(Math.random()*10);

int szam3=(int)(Math.random()*10);
int szam4=(int)(Math.random()*10);
int szam5=(int)(Math.random()*10);
int szam6=(int)(Math.random()*10);
int szam7=(int)(Math.random()*10);
int szam8=(int)(Math.random()*10);
int szam9=(int)(Math.random()*10);
int szam10=(int)(Math.random()*10);
//----------------------------------

    public Kilencevesek() {
        initComponents();
       
    }
    
     public Kilencevesek(Statement sta){
    initComponents();
    this.sta=sta;
     kezdés();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kilencevespalyak = new javax.swing.JTabbedPane();
        masodikpalya = new javax.swing.JPanel();
        v = new javax.swing.JTextField();
        v1 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        v5 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v7 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        v9 = new javax.swing.JTextField();
        romai = new javax.swing.JTextField();
        romai1 = new javax.swing.JTextField();
        romai2 = new javax.swing.JTextField();
        romai3 = new javax.swing.JTextField();
        romai4 = new javax.swing.JTextField();
        romai5 = new javax.swing.JTextField();
        romai6 = new javax.swing.JTextField();
        romai7 = new javax.swing.JTextField();
        romai8 = new javax.swing.JTextField();
        romai9 = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        pipa = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        pipa1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        pipa2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        pipa3 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        pipa4 = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        pipa5 = new javax.swing.JLabel();
        x6 = new javax.swing.JLabel();
        pipa6 = new javax.swing.JLabel();
        x7 = new javax.swing.JLabel();
        pipa7 = new javax.swing.JLabel();
        x8 = new javax.swing.JLabel();
        pipa8 = new javax.swing.JLabel();
        x9 = new javax.swing.JLabel();
        pipa9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        köv1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kilencevesek\n");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(865, 714));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        masodikpalya.setBackground(new java.awt.Color(102, 153, 255));
        masodikpalya.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        masodikpalya.setEnabled(false);
        masodikpalya.setMaximumSize(new java.awt.Dimension(0, 0));
        masodikpalya.setLayout(null);

        v.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v);
        v.setBounds(220, 190, 80, 64);

        v1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v1);
        v1.setBounds(220, 280, 80, 64);

        v2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v2);
        v2.setBounds(220, 390, 80, 64);

        v3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v3);
        v3.setBounds(220, 470, 80, 64);

        v4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });
        masodikpalya.add(v4);
        v4.setBounds(220, 570, 80, 64);

        v5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v5);
        v5.setBounds(640, 190, 80, 64);

        v6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v6);
        v6.setBounds(640, 280, 80, 64);

        v7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v7);
        v7.setBounds(640, 390, 80, 64);

        v8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });
        masodikpalya.add(v8);
        v8.setBounds(640, 480, 80, 64);

        v9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(v9);
        v9.setBounds(640, 570, 100, 64);

        romai.setEditable(false);
        romai.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai);
        romai.setBounds(90, 190, 110, 70);

        romai1.setEditable(false);
        romai1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai1);
        romai1.setBounds(20, 280, 180, 60);

        romai2.setEditable(false);
        romai2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai2);
        romai2.setBounds(20, 390, 180, 60);

        romai3.setEditable(false);
        romai3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai3);
        romai3.setBounds(20, 470, 180, 60);

        romai4.setEditable(false);
        romai4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai4);
        romai4.setBounds(20, 570, 180, 60);

        romai5.setEditable(false);
        romai5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai5);
        romai5.setBounds(440, 190, 190, 60);

        romai6.setEditable(false);
        romai6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai6);
        romai6.setBounds(440, 280, 190, 60);

        romai7.setEditable(false);
        romai7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai7);
        romai7.setBounds(440, 390, 190, 60);

        romai8.setEditable(false);
        romai8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai8);
        romai8.setBounds(440, 480, 190, 60);

        romai9.setEditable(false);
        romai9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        romai9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodikpalya.add(romai9);
        romai9.setBounds(440, 570, 190, 60);

        x.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x);
        x.setBounds(320, 190, 70, 60);

        pipa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa);
        pipa.setBounds(320, 190, 70, 60);

        x1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x1);
        x1.setBounds(320, 280, 70, 60);

        pipa1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa1);
        pipa1.setBounds(320, 280, 70, 60);

        x2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x2);
        x2.setBounds(320, 390, 70, 60);

        pipa2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa2);
        pipa2.setBounds(320, 390, 70, 60);

        x3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x3);
        x3.setBounds(320, 480, 70, 60);

        pipa3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa3);
        pipa3.setBounds(320, 480, 70, 60);

        x4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x4);
        x4.setBounds(320, 580, 70, 60);

        pipa4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa4);
        pipa4.setBounds(320, 580, 70, 60);

        x5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x5);
        x5.setBounds(740, 190, 70, 60);

        pipa5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa5);
        pipa5.setBounds(740, 190, 70, 60);

        x6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x6);
        x6.setBounds(740, 280, 70, 60);

        pipa6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa6);
        pipa6.setBounds(740, 280, 70, 60);

        x7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x7);
        x7.setBounds(740, 390, 70, 60);

        pipa7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa7);
        pipa7.setBounds(740, 390, 70, 60);

        x8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x8);
        x8.setBounds(740, 480, 70, 60);

        pipa8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa8);
        pipa8.setBounds(740, 480, 70, 60);

        x9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya.add(x9);
        x9.setBounds(750, 570, 70, 60);

        pipa9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya.add(pipa9);
        pipa9.setBounds(750, 570, 70, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("Ellenőrzés");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        masodikpalya.add(jButton1);
        jButton1.setBounds(10, 40, 170, 37);

        köv1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        köv1.setText("Következő pálya!");
        köv1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        köv1.setEnabled(false);
        köv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                köv1ActionPerformed(evt);
            }
        });
        masodikpalya.add(köv1);
        köv1.setBounds(10, 80, 237, 37);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Írd át a római számokat arab számokra!");
        masodikpalya.add(jLabel1);
        jLabel1.setBounds(10, 10, 470, 27);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "játékos kódja", "Neved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        masodikpalya.add(jScrollPane1);
        jScrollPane1.setBounds(570, 10, 200, 124);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("kattints a  nevedre!     --->");
        masodikpalya.add(jLabel7);
        jLabel7.setBounds(270, 90, 303, 27);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Ahhoz hogy pontot gyűjts, ");
        masodikpalya.add(jLabel6);
        jLabel6.setBounds(270, 60, 303, 27);

        kilencevespalyak.addTab("Első Páya", masodikpalya);

        getContentPane().add(kilencevespalyak);
        kilencevespalyak.setBounds(10, 0, 840, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v4ActionPerformed

    private void v8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   Játékműkődés();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void köv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_köv1ActionPerformed
        Kilenceves2 h1=new Kilenceves2(sta);
        h1.setVisible(true);
        dispose();
    }//GEN-LAST:event_köv1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        beolv();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int sor=jTable1.getSelectedRow();
        ID=Integer.parseInt(jTable1.getModel().getValueAt(sor, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kilencevesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kilencevesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kilencevesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kilencevesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kilencevesek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane kilencevespalyak;
    private javax.swing.JButton köv1;
    private javax.swing.JPanel masodikpalya;
    private javax.swing.JLabel pipa;
    private javax.swing.JLabel pipa1;
    private javax.swing.JLabel pipa2;
    private javax.swing.JLabel pipa3;
    private javax.swing.JLabel pipa4;
    private javax.swing.JLabel pipa5;
    private javax.swing.JLabel pipa6;
    private javax.swing.JLabel pipa7;
    private javax.swing.JLabel pipa8;
    private javax.swing.JLabel pipa9;
    private javax.swing.JTextField romai;
    private javax.swing.JTextField romai1;
    private javax.swing.JTextField romai2;
    private javax.swing.JTextField romai3;
    private javax.swing.JTextField romai4;
    private javax.swing.JTextField romai5;
    private javax.swing.JTextField romai6;
    private javax.swing.JTextField romai7;
    private javax.swing.JTextField romai8;
    private javax.swing.JTextField romai9;
    private javax.swing.JTextField v;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v5;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField v7;
    private javax.swing.JTextField v8;
    private javax.swing.JTextField v9;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    private javax.swing.JLabel x4;
    private javax.swing.JLabel x5;
    private javax.swing.JLabel x6;
    private javax.swing.JLabel x7;
    private javax.swing.JLabel x8;
    private javax.swing.JLabel x9;
    // End of variables declaration//GEN-END:variables

    private void kezdés() {
    romai.setText(tömb[szam]);
    romai1.setText(tömb2[szam2]);
    romai2.setText(tömb3[szam3]);
    romai3.setText(tömb4[szam4]);
    romai4.setText(tömb5[szam5]);
    romai5.setText(tömb6[szam6]);
    romai6.setText(tömb7[szam7]);
    romai7.setText(tömb8[szam8]);
    romai8.setText(tömb9[szam9]);
    romai9.setText(tömb10[szam10]);
     
    pipa.setVisible(false);
    pipa1.setVisible(false);
    pipa2.setVisible(false);
    pipa3.setVisible(false);
    pipa4.setVisible(false);
    pipa5.setVisible(false);
    pipa6.setVisible(false);
    pipa7.setVisible(false);
    pipa8.setVisible(false);
    pipa9.setVisible(false);
    
    x.setVisible(false);
    x1.setVisible(false);
    x2.setVisible(false);
    x3.setVisible(false);
    x4.setVisible(false);
    x5.setVisible(false);
    x6.setVisible(false);
    x7.setVisible(false);
    x8.setVisible(false);
    x9.setVisible(false);
    }

    private void Játékműkődés() {
    
         if(
         Integer.parseInt(v.getText())==1&&tömb[szam].equals("I")||
         Integer.parseInt(v.getText())==2&&tömb[szam].equals("II")||
         Integer.parseInt(v.getText())==3&&tömb[szam].equals("III")||
         Integer.parseInt(v.getText())==4&&tömb[szam].equals("IV")||
         Integer.parseInt(v.getText())==5&&tömb[szam].equals("V")||
         Integer.parseInt(v.getText())==6&&tömb[szam].equals("VI")||
         Integer.parseInt(v.getText())==7&&tömb[szam].equals("VII")||
         Integer.parseInt(v.getText())==8&&tömb[szam].equals("VIII")||
         Integer.parseInt(v.getText())==9&&tömb[szam].equals("IX")||              
         Integer.parseInt(v.getText())==10&&tömb[szam].equals("X")    
         )
        {pipa.setVisible(true); JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x.setVisible(true);
         }
        
        if(
         Integer.parseInt(v1.getText())==11&&tömb2[szam2].equals("XI")||
         Integer.parseInt(v1.getText())==12&&tömb2[szam2].equals("XII")||
         Integer.parseInt(v1.getText())==13&&tömb2[szam2].equals("XIII")||
         Integer.parseInt(v1.getText())==14&&tömb2[szam2].equals("XIV")||
         Integer.parseInt(v1.getText())==15&&tömb2[szam2].equals("XV")||
         Integer.parseInt(v1.getText())==16&&tömb2[szam2].equals("XVI")||
         Integer.parseInt(v1.getText())==17&&tömb2[szam2].equals("XVII")||
         Integer.parseInt(v1.getText())==18&&tömb2[szam2].equals("XVIII")||
         Integer.parseInt(v1.getText())==19&&tömb2[szam2].equals("XIX")||              
         Integer.parseInt(v1.getText())==20&&tömb2[szam2].equals("XX")    
         )
        {pipa1.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x1.setVisible(true);}
        
        if(
         Integer.parseInt(v2.getText())==21&&tömb3[szam3].equals("XXI")||
         Integer.parseInt(v2.getText())==22&&tömb3[szam3].equals("XXII")||
         Integer.parseInt(v2.getText())==23&&tömb3[szam3].equals("XXIII")||
         Integer.parseInt(v2.getText())==24&&tömb3[szam3].equals("XXIV")||
         Integer.parseInt(v2.getText())==25&&tömb3[szam3].equals("XXV")||
         Integer.parseInt(v2.getText())==26&&tömb3[szam3].equals("XXVI")||
         Integer.parseInt(v2.getText())==27&&tömb3[szam3].equals("XXVII")||
         Integer.parseInt(v2.getText())==28&&tömb3[szam3].equals("XXVIII")||
         Integer.parseInt(v2.getText())==29&&tömb3[szam3].equals("XXIX")||              
         Integer.parseInt(v2.getText())==30&&tömb3[szam3].equals("XXX")    
         )
        {pipa2.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x2.setVisible(true);} 
        
         if(
         Integer.parseInt(v3.getText())==31&&tömb4[szam4].equals("XXXI")||
         Integer.parseInt(v3.getText())==32&&tömb4[szam4].equals("XXXII")||
         Integer.parseInt(v3.getText())==33&&tömb4[szam4].equals("XXXIII")||
         Integer.parseInt(v3.getText())==34&&tömb4[szam4].equals("XXXIV")||
         Integer.parseInt(v3.getText())==35&&tömb4[szam4].equals("XXXV")||
         Integer.parseInt(v3.getText())==36&&tömb4[szam4].equals("XXXVI")||
         Integer.parseInt(v3.getText())==37&&tömb4[szam4].equals("XXXVII")||
         Integer.parseInt(v3.getText())==38&&tömb4[szam4].equals("XXXVIII")||
         Integer.parseInt(v3.getText())==39&&tömb4[szam4].equals("XXXIX")||              
         Integer.parseInt(v3.getText())==40&&tömb4[szam4].equals("XL")    
         )
        {pipa3.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x3.setVisible(true);} 
         
         if(
         Integer.parseInt(v4.getText())==41&&tömb5[szam5].equals("XLI")||
         Integer.parseInt(v4.getText())==42&&tömb5[szam5].equals("XLII")||
         Integer.parseInt(v4.getText())==43&&tömb5[szam5].equals("XLIII")||
         Integer.parseInt(v4.getText())==44&&tömb5[szam5].equals("XLIV")||
         Integer.parseInt(v4.getText())==45&&tömb5[szam5].equals("XLV")||
         Integer.parseInt(v4.getText())==46&&tömb5[szam5].equals("XLVI")||
         Integer.parseInt(v4.getText())==47&&tömb5[szam5].equals("XLVII")||
         Integer.parseInt(v4.getText())==48&&tömb5[szam5].equals("XLVIII")||
         Integer.parseInt(v4.getText())==49&&tömb5[szam5].equals("XLIX")||              
         Integer.parseInt(v4.getText())==50&&tömb5[szam5].equals("L")    
         )
        {pipa4.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x4.setVisible(true);} 

if(
         Integer.parseInt(v5.getText())==51&&tömb6[szam6].equals("LI")||
         Integer.parseInt(v5.getText())==52&&tömb6[szam6].equals("LII")||
         Integer.parseInt(v5.getText())==53&&tömb6[szam6].equals("LIII")||
         Integer.parseInt(v5.getText())==54&&tömb6[szam6].equals("LIV")||
         Integer.parseInt(v5.getText())==55&&tömb6[szam6].equals("LV")||
         Integer.parseInt(v5.getText())==56&&tömb6[szam6].equals("LVI")||
         Integer.parseInt(v5.getText())==57&&tömb6[szam6].equals("LVII")||
         Integer.parseInt(v5.getText())==58&&tömb6[szam6].equals("LVIII")||
         Integer.parseInt(v5.getText())==59&&tömb6[szam6].equals("LIX")||              
         Integer.parseInt(v5.getText())==60&&tömb6[szam6].equals("LX")    
         )
        {pipa5.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x5.setVisible(true);} 

if(
         Integer.parseInt(v6.getText())==61&&tömb7[szam7].equals("LXI")||
         Integer.parseInt(v6.getText())==62&&tömb7[szam7].equals("LXII")||
         Integer.parseInt(v6.getText())==63&&tömb7[szam7].equals("LXIII")||
         Integer.parseInt(v6.getText())==64&&tömb7[szam7].equals("LXIV")||
         Integer.parseInt(v6.getText())==65&&tömb7[szam7].equals("LXV")||
         Integer.parseInt(v6.getText())==66&&tömb7[szam7].equals("LXVI")||
         Integer.parseInt(v6.getText())==67&&tömb7[szam7].equals("LXVII")||
         Integer.parseInt(v6.getText())==68&&tömb7[szam7].equals("LXVIII")||
         Integer.parseInt(v6.getText())==69&&tömb7[szam7].equals("LXIX")||              
         Integer.parseInt(v6.getText())==70&&tömb7[szam7].equals("LXX")    
         )
        {pipa6.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x6.setVisible(true);} 

if(
         Integer.parseInt(v7.getText())==71&&tömb8[szam8].equals("LXXI")||
         Integer.parseInt(v7.getText())==72&&tömb8[szam8].equals("LXXII")||
         Integer.parseInt(v7.getText())==73&&tömb8[szam8].equals("LXXIII")||
         Integer.parseInt(v7.getText())==74&&tömb8[szam8].equals("LXXIV")||
         Integer.parseInt(v7.getText())==75&&tömb8[szam8].equals("LXXV")||
         Integer.parseInt(v7.getText())==76&&tömb8[szam8].equals("LXXVI")||
         Integer.parseInt(v7.getText())==77&&tömb8[szam8].equals("LXXVII")||
         Integer.parseInt(v7.getText())==78&&tömb8[szam8].equals("LXXVIII")||
         Integer.parseInt(v7.getText())==79&&tömb8[szam8].equals("LXXIX")||              
         Integer.parseInt(v7.getText())==80&&tömb8[szam8].equals("LXXX")    
         )
        {pipa7.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x7.setVisible(true);} 

if(
         Integer.parseInt(v8.getText())==81&&tömb9[szam9].equals("LXXXI")||
         Integer.parseInt(v8.getText())==82&&tömb9[szam9].equals("LXXXII")||
         Integer.parseInt(v8.getText())==83&&tömb9[szam9].equals("LXXXIII")||
         Integer.parseInt(v8.getText())==84&&tömb9[szam9].equals("LXXXIV")||
         Integer.parseInt(v8.getText())==85&&tömb9[szam9].equals("LXXXV")||
         Integer.parseInt(v8.getText())==86&&tömb9[szam9].equals("LXXXVI")||
         Integer.parseInt(v8.getText())==87&&tömb9[szam9].equals("LXXXVII")||
         Integer.parseInt(v8.getText())==88&&tömb9[szam9].equals("LXXXVIII")||
         Integer.parseInt(v8.getText())==89&&tömb9[szam9].equals("LXXXIX")||              
         Integer.parseInt(v8.getText())==90&&tömb9[szam9].equals("XC")    
         )
        {pipa8.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x8.setVisible(true);} 

if(
         Integer.parseInt(v9.getText())==91&&tömb10[szam10].equals("XCI")||
         Integer.parseInt(v9.getText())==92&&tömb10[szam10].equals("XCII")||
         Integer.parseInt(v9.getText())==93&&tömb10[szam10].equals("XCIII")||
         Integer.parseInt(v9.getText())==94&&tömb10[szam10].equals("XCIV")||
         Integer.parseInt(v9.getText())==95&&tömb10[szam10].equals("XCV")||
         Integer.parseInt(v9.getText())==96&&tömb10[szam10].equals("XCVI")||
         Integer.parseInt(v9.getText())==97&&tömb10[szam10].equals("XCVII")||
         Integer.parseInt(v9.getText())==98&&tömb10[szam10].equals("XCVIII")||
         Integer.parseInt(v9.getText())==99&&tömb10[szam10].equals("XCIX")||              
         Integer.parseInt(v9.getText())==100&&tömb10[szam10].equals("C")    
         )
        {pipa9.setVisible(true);JOptionPane.showMessageDialog(null, "SZÉP VOLT! :D ");adat();}
        else{x9.setVisible(true);}    
jButton1.setEnabled(false);
köv1.setEnabled(true);

    }

    private void beolv() {
     DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
try{
        Connection con=DriverManager.getConnection(host,user,pass);
        String sql="SELECT * FROM játékosadatok";
        Statement sta=con.createStatement();
        ResultSet rs=sta.executeQuery(sql);
        while(rs.next())
        {
         model.addRow(new Object[]{rs.getInt("id"),rs.getString("nev")});
         }
        sta.close();
        con.close();
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Hiba a beolvasás");}

    }

    private void adat() {
     try{
   Connection con=DriverManager.getConnection(host,user,pass);
     String sql="UPDATE játékosadatok SET "
   +"pontszam=pontszam+1"
   +" WHERE id="+ID;
   
   Statement sta=con.createStatement();
   sta.executeUpdate(sql);
   sta.close();
   con.close();
 //  JOptionPane.showMessageDialog(null, "JÁR A PONT"); ELLENŐRÉS SZEMPONTJÁBÓL
  }
  catch(SQLException e)
{
JOptionPane.showMessageDialog(null, "Hiba");}


    }
    }
