/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csomag;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mikey
 */
public class Kilenceves2 extends javax.swing.JFrame {
      private Statement sta;
  String host="jdbc:mysql://localhost:3306/vizsga";
String user="root";
String pass="root";
private int  ID;

//1-től-500-ig számok
 Random rand = new Random(); 
    int r1 =rand.nextInt(500)+1;    
    int r2 =rand.nextInt(500)+1;
    int r3 =rand.nextInt(500)+1;
    int r4 =rand.nextInt(500)+1;
    
    int r5 =(int)(Math.random() * 501)+500;  // 500-től 1000-ig
    int r6 =rand.nextInt(500)+1;
    int r7 =(int)(Math.random() * 501)+500;  // 500-től 1000-ig
    int r8 =rand.nextInt(500)+1;
    
    int r9 =rand.nextInt(100)+1;
    int r10 =rand.nextInt(10)+1;
    int r11 =rand.nextInt(100)+1;
    int r12 =rand.nextInt(10)+1;
    
    int[] tömb ={80,72,32,48};
    int r13 =8;
    int[] tömb1 ={70,63,56,49};
    int r14 =7;
int szam=(int)(Math.random()*4);
int szam1=(int)(Math.random()*4);
  



    public Kilenceves2() {
        initComponents();
      
    }
    
    public Kilenceves2(Statement sta){
    initComponents();
    this.sta=sta;
      kezdés();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kilencevespalyak3 = new javax.swing.JTabbedPane();
        masodikpalya3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        köv4 = new javax.swing.JButton();
        elso = new javax.swing.JTextField();
        elso2 = new javax.swing.JTextField();
        elso3 = new javax.swing.JTextField();
        elso4 = new javax.swing.JTextField();
        elso5 = new javax.swing.JTextField();
        elso6 = new javax.swing.JTextField();
        elso7 = new javax.swing.JTextField();
        elso8 = new javax.swing.JTextField();
        masodik = new javax.swing.JTextField();
        masodik2 = new javax.swing.JTextField();
        masodik3 = new javax.swing.JTextField();
        masodik4 = new javax.swing.JTextField();
        masodik5 = new javax.swing.JTextField();
        masodik6 = new javax.swing.JTextField();
        masodik7 = new javax.swing.JTextField();
        masodik8 = new javax.swing.JTextField();
        v = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        v5 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v7 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        egomb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        x6 = new javax.swing.JLabel();
        x7 = new javax.swing.JLabel();
        pipa = new javax.swing.JLabel();
        pipa1 = new javax.swing.JLabel();
        pipa2 = new javax.swing.JLabel();
        pipa3 = new javax.swing.JLabel();
        pipa4 = new javax.swing.JLabel();
        pipa5 = new javax.swing.JLabel();
        pipa6 = new javax.swing.JLabel();
        pipa7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kilencéves2");
        setPreferredSize(new java.awt.Dimension(1133, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        masodikpalya3.setBackground(new java.awt.Color(102, 153, 255));
        masodikpalya3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        masodikpalya3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Számitsd ki a válaszokat!");
        masodikpalya3.add(jLabel4);
        jLabel4.setBounds(12, 0, 278, 37);

        köv4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        köv4.setText("Következő pálya!");
        köv4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        köv4.setEnabled(false);
        köv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                köv4ActionPerformed(evt);
            }
        });
        masodikpalya3.add(köv4);
        köv4.setBounds(20, 130, 237, 37);

        elso.setEditable(false);
        elso.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elsoActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso);
        elso.setBounds(20, 210, 90, 57);

        elso2.setEditable(false);
        elso2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso2ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso2);
        elso2.setBounds(20, 300, 90, 58);

        elso3.setEditable(false);
        elso3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso3ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso3);
        elso3.setBounds(20, 390, 90, 57);

        elso4.setEditable(false);
        elso4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso4ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso4);
        elso4.setBounds(20, 470, 90, 57);

        elso5.setEditable(false);
        elso5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso5ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso5);
        elso5.setBounds(590, 200, 80, 57);

        elso6.setEditable(false);
        elso6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso6ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso6);
        elso6.setBounds(590, 300, 80, 57);

        elso7.setEditable(false);
        elso7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso7ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso7);
        elso7.setBounds(590, 380, 80, 57);

        elso8.setEditable(false);
        elso8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        elso8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elso8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elso8ActionPerformed(evt);
            }
        });
        masodikpalya3.add(elso8);
        elso8.setBounds(590, 490, 80, 57);

        masodik.setEditable(false);
        masodik.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodikActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik);
        masodik.setBounds(210, 210, 90, 57);

        masodik2.setEditable(false);
        masodik2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik2ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik2);
        masodik2.setBounds(210, 300, 90, 57);

        masodik3.setEditable(false);
        masodik3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik3ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik3);
        masodik3.setBounds(210, 400, 90, 57);

        masodik4.setEditable(false);
        masodik4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik4ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik4);
        masodik4.setBounds(210, 480, 90, 57);

        masodik5.setEditable(false);
        masodik5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik5ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik5);
        masodik5.setBounds(760, 200, 80, 57);

        masodik6.setEditable(false);
        masodik6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik6ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik6);
        masodik6.setBounds(760, 310, 80, 57);

        masodik7.setEditable(false);
        masodik7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik7ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik7);
        masodik7.setBounds(760, 390, 80, 57);

        masodik8.setEditable(false);
        masodik8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        masodik8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        masodik8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masodik8ActionPerformed(evt);
            }
        });
        masodikpalya3.add(masodik8);
        masodik8.setBounds(760, 500, 80, 57);

        v.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });
        masodikpalya3.add(v);
        v.setBounds(380, 210, 80, 57);

        v2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v2);
        v2.setBounds(370, 300, 80, 57);

        v3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v3);
        v3.setBounds(390, 400, 80, 57);

        v4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v4);
        v4.setBounds(380, 480, 80, 57);

        v5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v5);
        v5.setBounds(930, 200, 80, 57);

        v6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v6);
        v6.setBounds(930, 310, 80, 57);

        v7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v7ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v7);
        v7.setBounds(930, 390, 80, 57);

        v8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });
        masodikpalya3.add(v8);
        v8.setBounds(930, 500, 80, 57);

        egomb.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        egomb.setText("Ellenőrzés");
        egomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egombActionPerformed(evt);
            }
        });
        masodikpalya3.add(egomb);
        egomb.setBounds(20, 80, 155, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText(" Végül kattints az elenőrzésre!");
        masodikpalya3.add(jLabel5);
        jLabel5.setBounds(10, 40, 335, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hozzáad.png"))); // NOI18N
        masodikpalya3.add(jLabel6);
        jLabel6.setBounds(130, 210, 60, 57);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hozzáad.png"))); // NOI18N
        masodikpalya3.add(jLabel7);
        jLabel7.setBounds(120, 300, 60, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kivonas.png"))); // NOI18N
        masodikpalya3.add(jLabel8);
        jLabel8.setBounds(120, 390, 56, 57);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/szorzás.png"))); // NOI18N
        masodikpalya3.add(jLabel9);
        jLabel9.setBounds(690, 200, 66, 57);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kivonas.png"))); // NOI18N
        masodikpalya3.add(jLabel10);
        jLabel10.setBounds(130, 470, 60, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/szorzás.png"))); // NOI18N
        masodikpalya3.add(jLabel11);
        jLabel11.setBounds(690, 310, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel12);
        jLabel12.setBounds(310, 210, 62, 58);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel13);
        jLabel13.setBounds(310, 400, 62, 58);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/egyenlo.png"))); // NOI18N
        masodikpalya3.add(jLabel14);
        jLabel14.setBounds(310, 480, 62, 58);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel15);
        jLabel15.setBounds(860, 200, 62, 58);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel16);
        jLabel16.setBounds(300, 300, 62, 58);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel17);
        jLabel17.setBounds(860, 310, 62, 58);

        x.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x);
        x.setBounds(480, 210, 70, 60);

        x1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x1);
        x1.setBounds(480, 300, 70, 60);

        x2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x2);
        x2.setBounds(490, 400, 70, 60);

        x3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x3);
        x3.setBounds(490, 480, 70, 60);

        x4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x4);
        x4.setBounds(1020, 200, 70, 60);

        x5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x5);
        x5.setBounds(1030, 310, 70, 60);

        x6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x6);
        x6.setBounds(1020, 390, 70, 60);

        x7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\hiba.png")); // NOI18N
        masodikpalya3.add(x7);
        x7.setBounds(1030, 500, 70, 60);

        pipa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa);
        pipa.setBounds(480, 210, 70, 60);

        pipa1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa1);
        pipa1.setBounds(480, 300, 70, 60);

        pipa2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa2);
        pipa2.setBounds(490, 400, 70, 60);

        pipa3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa3);
        pipa3.setBounds(490, 480, 70, 60);

        pipa4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa4);
        pipa4.setBounds(1020, 200, 70, 60);

        pipa5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa5);
        pipa5.setBounds(1030, 310, 70, 60);

        pipa6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa6);
        pipa6.setBounds(1020, 390, 70, 60);

        pipa7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\pipa.png")); // NOI18N
        masodikpalya3.add(pipa7);
        pipa7.setBounds(1030, 500, 70, 60);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/osztás.png"))); // NOI18N
        masodikpalya3.add(jLabel27);
        jLabel27.setBounds(690, 390, 60, 60);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel28);
        jLabel28.setBounds(860, 390, 62, 58);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/osztás.png"))); // NOI18N
        masodikpalya3.add(jLabel29);
        jLabel29.setBounds(690, 490, 60, 60);

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mikey\\OneDrive\\Dokumentumok\\NetBeansProjects\\Számithatszrám\\src\\kepek\\egyenlo.png")); // NOI18N
        masodikpalya3.add(jLabel30);
        jLabel30.setBounds(860, 500, 62, 58);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "játékos kódja", "Neved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        masodikpalya3.add(jScrollPane1);
        jScrollPane1.setBounds(660, 10, 200, 124);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setText("kattints a  nevedre!     --->");
        masodikpalya3.add(jLabel18);
        jLabel18.setBounds(360, 50, 303, 27);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText("Ahhoz hogy pontot gyűjts, ");
        masodikpalya3.add(jLabel19);
        jLabel19.setBounds(360, 20, 303, 27);

        kilencevespalyak3.addTab("Második pálya", masodikpalya3);

        getContentPane().add(kilencevespalyak3);
        kilencevespalyak3.setBounds(0, 20, 1120, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void köv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_köv4ActionPerformed

        Kilenceves3 h1=new Kilenceves3(sta);
        h1.setVisible(true);
        dispose();
    }//GEN-LAST:event_köv4ActionPerformed

    private void elsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elsoActionPerformed

    }//GEN-LAST:event_elsoActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed

    }//GEN-LAST:event_vActionPerformed

    private void masodikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodikActionPerformed

    }//GEN-LAST:event_masodikActionPerformed

    private void elso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso3ActionPerformed

    }//GEN-LAST:event_elso3ActionPerformed

    private void masodik3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik3ActionPerformed

    }//GEN-LAST:event_masodik3ActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed

    }//GEN-LAST:event_v3ActionPerformed

    private void elso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso5ActionPerformed

    }//GEN-LAST:event_elso5ActionPerformed

    private void masodik5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik5ActionPerformed

    }//GEN-LAST:event_masodik5ActionPerformed

    private void v5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v5ActionPerformed

    }//GEN-LAST:event_v5ActionPerformed

    private void elso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso2ActionPerformed

    }//GEN-LAST:event_elso2ActionPerformed

    private void masodik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik2ActionPerformed

    }//GEN-LAST:event_masodik2ActionPerformed

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed

    }//GEN-LAST:event_v2ActionPerformed

    private void elso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso6ActionPerformed

    }//GEN-LAST:event_elso6ActionPerformed

    private void masodik4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik4ActionPerformed

    }//GEN-LAST:event_masodik4ActionPerformed

    private void v6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6ActionPerformed

    }//GEN-LAST:event_v6ActionPerformed

    private void elso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso4ActionPerformed

    }//GEN-LAST:event_elso4ActionPerformed

    private void masodik6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik6ActionPerformed

    }//GEN-LAST:event_masodik6ActionPerformed

    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed

    }//GEN-LAST:event_v4ActionPerformed

    private void egombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egombActionPerformed
Gomb();
    

    }//GEN-LAST:event_egombActionPerformed

    private void elso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elso7ActionPerformed

    private void masodik7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masodik7ActionPerformed

    private void v7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v7ActionPerformed

    private void elso8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elso8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elso8ActionPerformed

    private void masodik8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masodik8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masodik8ActionPerformed

    private void v8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      beolv();
 
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int sor=jTable1.getSelectedRow();
        ID=Integer.parseInt(jTable1.getModel().getValueAt(sor, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kilenceves2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kilenceves2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kilenceves2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kilenceves2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kilenceves2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton egomb;
    private javax.swing.JTextField elso;
    private javax.swing.JTextField elso2;
    private javax.swing.JTextField elso3;
    private javax.swing.JTextField elso4;
    private javax.swing.JTextField elso5;
    private javax.swing.JTextField elso6;
    private javax.swing.JTextField elso7;
    private javax.swing.JTextField elso8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane kilencevespalyak3;
    private javax.swing.JButton köv4;
    private javax.swing.JTextField masodik;
    private javax.swing.JTextField masodik2;
    private javax.swing.JTextField masodik3;
    private javax.swing.JTextField masodik4;
    private javax.swing.JTextField masodik5;
    private javax.swing.JTextField masodik6;
    private javax.swing.JTextField masodik7;
    private javax.swing.JTextField masodik8;
    private javax.swing.JPanel masodikpalya3;
    private javax.swing.JLabel pipa;
    private javax.swing.JLabel pipa1;
    private javax.swing.JLabel pipa2;
    private javax.swing.JLabel pipa3;
    private javax.swing.JLabel pipa4;
    private javax.swing.JLabel pipa5;
    private javax.swing.JLabel pipa6;
    private javax.swing.JLabel pipa7;
    private javax.swing.JTextField v;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v5;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField v7;
    private javax.swing.JTextField v8;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    private javax.swing.JLabel x4;
    private javax.swing.JLabel x5;
    private javax.swing.JLabel x6;
    private javax.swing.JLabel x7;
    // End of variables declaration//GEN-END:variables

    private void kezdés() {
        
      elso.setText(Integer.toString(r1));
      masodik.setText(Integer.toString(r2));
      elso2.setText(Integer.toString(r3));
      masodik2.setText(Integer.toString(r4));
      
       elso3.setText(Integer.toString(r5));
      masodik3.setText(Integer.toString(r6));
      elso4.setText(Integer.toString(r7));
      masodik4.setText(Integer.toString(r8));
      
        elso5.setText(Integer.toString(r9));
      masodik5.setText(Integer.toString(r10));
      elso6.setText(Integer.toString(r11));
      masodik6.setText(Integer.toString(r12));
      
       elso7.setText(Integer.toString(tömb[szam]));
      masodik7.setText(Integer.toString(r13));
      elso8.setText(Integer.toString(tömb1[szam1]));
      masodik8.setText(Integer.toString(r14));
      
      //képek
      x.setVisible(false);
      x1.setVisible(false);
      x2.setVisible(false);
      x3.setVisible(false);   
      x4.setVisible(false);
      x5.setVisible(false);
      x6.setVisible(false);
      x7.setVisible(false);
      pipa.setVisible(false);
      pipa1.setVisible(false);
      pipa2.setVisible(false);
      pipa3.setVisible(false);
      pipa4.setVisible(false);
      pipa5.setVisible(false);
      pipa6.setVisible(false);
      pipa7.setVisible(false);
    }

    private void adat() {
       try{
   Connection con=DriverManager.getConnection(host,user,pass);
     String sql="UPDATE játékosadatok SET "
   +"pontszam=pontszam+1"
   +" WHERE id="+ID;
   
   Statement sta=con.createStatement();
   sta.executeUpdate(sql);
   sta.close();
   con.close();
 //  JOptionPane.showMessageDialog(null, "JÁR A PONT"); ELLENŐRÉS SZEMPONTJÁBÓL
  }
  catch(SQLException e)
{
JOptionPane.showMessageDialog(null, "Hiba");}

    }

    private void Gomb() {
         if(r1+r2==Integer.parseInt(v.getText())){ //ELSŐ ÖSSZEADÁS
            pipa.setVisible(true);
            adat();
        }else{x.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SEBAJ!  A válasz volt: "+r1+"+"+r2+"="+(r1+r2) );}

        if(r3+r4==Integer.parseInt(v2.getText())){  //MÁSODIK
            pipa1.setVisible(true);
            adat();
        }else{x1.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ!  A válasz volt: "+r3+"+"+r4+"="+(r3+r4));}

        if(r5-r6==Integer.parseInt(v3.getText())){ //HARMADIK KIVONÁS
            pipa2.setVisible(true);
            adat();
        }else{x2.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt: "+r5+"-"+r6+"="+(r5-r6));}

        if(r7-r8==Integer.parseInt(v4.getText())){ //NEGYEDIK
            pipa3.setVisible(true);
            adat();
        }else{x3.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt: "+r7+"-"+r8+"="+(r7-r8));}

        if(r9*r10==Integer.parseInt(v5.getText())){   //ÖTÖDIK SZORZÁS
            pipa4.setVisible(true);
            adat();
        }else{x4.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt: "+r9+"*"+r10+"="+(r9*r10));}

        if(r11*r12==Integer.parseInt(v6.getText())){  //HATODIK
            pipa5.setVisible(true);
            adat();
        }else{x5.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt:  "+r11+"x"+r12+"="+(r11*r12));}
      
        if(tömb[szam]/r13==Integer.parseInt(v7.getText())){  //HETEDIK OSZTÁS
            pipa6.setVisible(true);
            adat();
        }else{x6.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt:  "+tömb[szam]+":"+r13+"="+(tömb[szam]/r13));}
         
         if(tömb1[szam1]/r14==Integer.parseInt(v8.getText())){  //NYOLCADIK
          pipa7.setVisible(true);
            adat();
        }else{x7.setVisible(true);JOptionPane.showMessageDialog(null, "AJJAJ, SE BAJ! :) A válasz volt:  "+tömb1[szam1]+":"+r14+"="+(tömb1[szam1]/r14));}
         egomb.setEnabled(false);
        köv4.setEnabled(true);
        egomb.setEnabled(false);
    }

    private void beolv() {
          DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
try{
        Connection con=DriverManager.getConnection(host,user,pass);
        String sql="SELECT * FROM játékosadatok";
        Statement sta=con.createStatement();
        ResultSet rs=sta.executeQuery(sql);
        while(rs.next())
        {
          model.addRow(new Object[]{rs.getInt("id"),rs.getString("nev")});
         }
        sta.close();
        con.close();
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Hiba a beolvasás");}
    }
}
